/* eslint-disable */
// This file is auto-generated by Convex.
// Run `npx convex dev` to regenerate.

import type { FunctionReference } from "convex/server";

export const api: Record<string, Record<string, FunctionReference<any, any>>> = {} as any;
export const internal: Record<string, Record<string, FunctionReference<any, any>>> = {} as any;
