/* eslint-disable */
// This file is auto-generated by Convex.
// Run `npx convex dev` to regenerate.

import type { GenericDataModel } from "convex/server";

export type DataModel = GenericDataModel;
