/* eslint-disable */
// This file is auto-generated by Convex.
// Run `npx convex dev` to regenerate.

import {
    actionGeneric,
    httpActionGeneric,
    queryGeneric,
    mutationGeneric,
    internalActionGeneric,
    internalMutationGeneric,
    internalQueryGeneric,
} from "convex/server";
import type { DataModel } from "./dataModel";

export const query = queryGeneric as any;
export const mutation = mutationGeneric as any;
export const action = actionGeneric as any;
export const httpAction = httpActionGeneric as any;
export const internalQuery = internalQueryGeneric as any;
export const internalMutation = internalMutationGeneric as any;
export const internalAction = internalActionGeneric as any;
